# map metagenomic reads to a reference (assembly or ref genomes)

# HTCondor Universe
universe = vanilla
log = meta_mapping_$(Cluster).log
error = meta_mapping_$(Cluster)_$(Process).err
requirements = (OpSys == "LINUX") && (Target.HasGluster == true) && (OpSysMajorVer =?= 7)

# Exectuables
executable = executables/map-metas-to-refs.sh
arguments = $(ref) $(meta) $(outname)
output = meta_mapping_$(Cluster).out

# Transferring Files
# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
transfer_input_files = /home/emcdaniel/software/BBMap_38.07.tar.gz,/home/emcdaniel/software/samtools.tar.gz

# Compute resources
request_cpus = 4
request_memory = 250GB
request_disk = 200GB


queue ref,meta,outname from metadata/queues/geodes-mapping-sample6-redo.txt
