################
# mapMetasToRefs.sub
# Submission script for mapping metagenomic reads to a ref genome or assembly
# Elizabeth McDaniel


request_cpus = 4
request_memory = 10GB

executable = /home/GLBRCORG/emcdaniel/Lake-MAGs/executables/mapMetasToRefs.sh
arguments = $(ref) $(meta) $(out)

output = /home/GLBRCORG/emcdaniel/Lake-MAGs/outs/$(Cluster)_$(Process)_mapping.out
error = /home/GLBRCORG/emcdaniel/Lake-MAGs/errs/$(Cluster)_$(Process)_mapping.err
log = /home/GLBRCORG/emcdaniel/Lake-MAGs/logs/$(Cluster)_$(Process)_mapping.log

queue ref,meta,out from /home/GLBRCORG/emcdaniel/Lake-MAGs/metadata/mendota-mappingCombos.txt
