##################
# metabat_binning.sub
# Submission script for binning on GLBRC with MetaBat
# Elizabeth McDaniel
##################

request_cpus = 4
request_memory = 5GB

executable = /home/GLBRCORG/emcdaniel/Lake-MAGs/executables/binning-metabat.sh
arguments = $(ASSEMB)

output = /home/GLBRCORG/emcdaniel/Lake-MAGs/outs/$(Cluster)_$(Process)_binning.out
error = /home/GLBRCORG/emcdaniel/Lake-MAGs/errs/$(Cluster)_$(Process)_binning.err
log = /home/GLBRCORG/emcdaniel/Lake-MAGs/logs/$(Cluster)_$(Process)_binning.log

queue ASSEMB from /home/GLBRCORG/emcdaniel/Lake-MAGs/metadata/mendota-assemblies.txt
