# raw metagenomic reads quality filtering

# HTCondor Universe
universe = vanilla
log = meta_qc_$(Cluster).log
error = meta_qc_$(Cluster)_$(Process).err
requirements = (Target.HasGluster == true)

# Exectuables
executable = executables/qc-metagenomes.sh
arguments = $(meta)
output = meta_qc_$(Cluster).out

# Transferring Files
# should_transfer_files = YES
# when_to_transfer_output = ON_EXIT
transfer_input_files = /home/emcdaniel/software/BBMap_38.07.tar.gz

# Compute resources
request_cpus = 4
request_memory = 30GB
request_disk = 100GB

queue meta from metadata/queues/metaToQC.txt
